### ISSUE TITLE
Interrupting MessageRetrievers while they are retrieving messages swallows interruption

### ISSUE THREAD

**Issue by JaidenAshmore** [JaidenAshmore/java-dynamic-sqs-listener#119]
Due to the SqsAsyncClient swallowing an exception and throwing their own exception there is a race condition where shutting down the background threads will not complete for the MessageRetrievers.  The exception structure can be seen here:

![image](https://user-images.githubusercontent.com/1059637/59815164-67e50200-92dd-11e9-8a73-b39366aef63d.png)

**Comment by Ortimer** [comment]
Hello Jaiden, I'm in version 3.0.0 and I'm seeing this kind of behavior, looks like there may be a regression with this bug.

**Comment by JaidenAshmore** [comment]
Hmm damn. Let me take a look

**Comment by JaidenAshmore** [comment]
Hey @Ortimer I have done a quick look at the code that could be causing it and theoretically it shouldn't be a problem. It could be a different problem with this same code or I am misinterpreting some of this code.

Are you seeing any errors logs, more specifically is the retriever not actually shutting down and you eventually see a message like this after 60 seconds (the default) or whatever you have it customised as:

```java
log.error("MessageRetriever did not shutdown within {} seconds", retrieverShutdownTimeoutInSeconds);
```

If you see this message then yes something is definitely causing it to not shutdown properly.

**Comment by Ortimer** [comment]
Mmmmm I'm actually seeing `MessageResolver has been successfully stopped` so it may be a totally different bug then. Sorry for wasting your time.
I though it was related to this bug since the locked thread is the message broker and I got it fixed by downgrading my version.

**Comment by Ortimer** [comment]
Just in case this is the thread bump of the locked thread
```
Name: sqs-consumer-service-ingest-message-message-broker
State: WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@fb55974
Total blocked: 0  Total waited: 3

Stack trace: 
java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
java.base@11.0.5/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
```

**Comment by JaidenAshmore** [comment]
awesome that helps a lot. Looks like it is the message broker that is causing problems. I'll close this again and create a new bug for this

**Comment by JaidenAshmore** [comment]
@Ortimer I couldn't tag you in the other bug that I created: https://github.com/JaidenAshmore/java-dynamic-sqs-listener/issues/151 but it looks like an easy fix, expect a patch release in the next few days.
