### ISSUE TITLE
QueueListerner does not work with AmazonSqsAsync

### ISSUE THREAD

**Issue by caiaffa** [JaidenAshmore/java-dynamic-sqs-listener#138]
`@Bean
    public AmazonSQSAsync amazonSqs() {

        return new LatencyAppliedAmazonSqsAsync(AmazonSQSAsyncClientBuilder.standard()
                .withRegion(Regions.US_EAST_1)
                .build());
    }`

//    @QueueListener(value = "example", concurrencyLevel = 10)

**Comment by JaidenAshmore** [comment]
Hey,

This library does not support the old AWS SDK so you can either upgrade your service to only use the newer SDK or you can supply two beans, one for the old `AmazonSQSAsync` and the other the newer `SqsAsyncClient`.
