### ISSUE TITLE
MessageBroker ExecutorService is not shutdown when container shuts down

### ISSUE THREAD

**Issue by JaidenAshmore** [JaidenAshmore/java-dynamic-sqs-listener#151]
Looks like the message broker is locked or continually spinning on shutdown. Will need to dig into this.

```
Name: sqs-consumer-service-ingest-message-message-broker
State: WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@fb55974
Total blocked: 0  Total waited: 3

Stack trace: 
java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
java.base@11.0.5/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
java.base@11.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
java.base@11.0.5/java.lang.Thread.run(Thread.java:834)
```

**Comment by JaidenAshmore** [comment]
Hey @Ortimer,

So I have run this [example](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/blob/3.x/examples/spring-starter-examples/src/main/java/com/jashmore/sqs/examples/Application.java) which has a couple of message listeners and will shutdown and startup the container over a scheduled period.

What I have seen is that the message-broker `ExecutorService` is not being shutdown when the container is being shutdown (e.g. on a shutdown or when you manually stop the container). The result is that these message broker threads are just sitting there not doing anything until it starts up. 

When looking at 3.0.0 I was seeing that when the container started back up I was getting duplicate threads with the same name as it started a new executor service with the same name. For some reason I was only seeing it go up to 3 duplicates but I would have expected it to keep growing, not sure why.

Anyway the fix should be easy, just need to shutdown the executor service. Should be in the next patch release soon.

**Comment by Ortimer** [comment]
Thanks a lot for looking at this

**Comment by JaidenAshmore** [comment]
Publishing 3.1.1 to the maven repository now, hopefully should be able to be pulled down within half an hour. Let me know if this fixes your problem.

**Comment by Ortimer** [comment]
Thanks a lot, will check it out tomorrow.

**Comment by Ortimer** [comment]
Sorry it took me 3 days to respond, it worked like a charm, thanks a lot
