### ISSUE TITLE
ObjectMapper from QueueListenerConfiguration.CoreArgumentResolversConfiguration can override spring-boot mapper

### ISSUE THREAD

**Issue by stephencassidy-r7** [JaidenAshmore/java-dynamic-sqs-listener#217]
I may have just encountered an edge-case when using both 3.X.X and 4.X.X - when using the spring-starter, the ObjectMapper in CoreArgumentResolversConfiguration can get created and override the spring-boot configured mapper (it seems to interfere with [JacksonAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jackson/JacksonAutoConfiguration.java).

I only noticed this issue when applications that used additional modules such as Kotlin were no longer able to deserialise requests - adding my own ArgumentResolverService fixed the issue.

Not sure if there is a better way around this besides providing your own ArgumentResolverService bean, or if an additional check on the ObjectMapper bean would prevent it overriding the Spring one 🤔 

Just incase it's useful -
- Spring Boot - 2.2.4.RELEASE
- java-dynamic-sqs-listener - 4.0.0-M7

**Comment by JaidenAshmore** [comment]
Ah darn that isn't a great experience, sorry about that. Should be an easy fix, I will have a 3.1.2 and 4.0.0-M8 released by the end of the day

**Comment by stephencassidy-r7** [comment]
@JaidenAshmore Cheers for the quick reply - don't worry, I think I might be one of the few people with this issue anyways 😉

**Comment by JaidenAshmore** [comment]
I have made some changes, so will release 4.0.0-M8 in an hour or two. 

I will just release it onto the 4.x branch for now but let me know if you want it on the 3.x version and I can cherry pick it back and release that.

**Comment by stephencassidy-r7** [comment]
> I have made some changes, so will release 4.0.0-M8 in an hour or two.
> 
> I will just release it onto the 4.x branch for now but let me know if you want it on the 3.x version and I can cherry pick it back and release that.

Cheers, the 4.x branch for now is perfect 👍

**Comment by JaidenAshmore** [comment]
Hey, I have released 4.0.0-M8. Let me know if that didn't fix the problem you were having and I can take another look :)
