### ISSUE TITLE
Compile issue with com.commercehub.gradle.plugin.avro-base

### ISSUE THREAD

**Issue by kschroiff** [JaidenAshmore/java-dynamic-sqs-listener#359]
It seems that the dependency com.commercehub.gradle.plugin.avro-base 0.21.0 has been withdrawn from the repositories?

I've tried the latest version 0.99.99 instead but this results in a compile error.

PS: It would be good to document that messages are fetched with a 30sec vis timeout default - regardless of the settings in the queue. That being said - why override the queue settings in the first place? It took me a couple of hours to find out why we had so many duplicates detected despite a long vis timeout defined in the queue. I almost thought it was an AWS bug.

**Comment by JaidenAshmore** [comment]
I'll take a look!

> That being said - why override the queue settings in the first place?

Yep completely agree, I'll create a ticket to remove this

**Comment by JaidenAshmore** [comment]
Looks to be compiling correctly now, I created #365 to remove that default value
