### ISSUE TITLE
Does this library work with a Springboot v3 application?

### ISSUE THREAD

**Issue by vineet-katta** [JaidenAshmore/java-dynamic-sqs-listener#395]
Our current springboot app is on version 2.7.11, using this library. We are upgrading it to v3. Will this library support the app on v3?

**Comment by JaidenAshmore** [comment]
I probably won't do any work to actively support it but if there are fixes that need to be made I am happy to review submissions. I dunno if the v3 would have significant problems with this library

**Comment by flauschie** [comment]
Does this mean that you consider this library deprecated now?

It's quite central to our service but I don't think that we have the resources to do any patching.

**Comment by JaidenAshmore** [comment]
This has been made compatible with Spring Boot 3 in the [6.0.0](https://github.com/JaidenAshmore/java-dynamic-sqs-listener/releases/tag/v6.0.0) version of the library. No changes are needing to be made to make this library work but you will need to do your own upgrade to Spring Boot 3/Java 17.
